apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-confmap
  namespace: my-sample-namespace
data:
  nginx.conf: |- 
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        default_type application/octet-stream;

        upstream wp-backend {
            server wp-service:80;
        }

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        sendfile on;
        keepalive_timeout 65;

        server {
            listen 80;
            
            location /status {
              stub_status;
            }

            location / {
                proxy_pass http://wp-backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-sample-namespace
  labels:
    app: nginx
spec: 
  type: LoadBalancer                  # external service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
  namespace: my-sample-namespace
  labels:
    app: nginx
spec:                  # external service
  ports:
  - protocol: TCP
    port: 9113
    targetPort: 9113
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-sample-namespace
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9113"
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginxconf
        configMap:
          # defaultMode: 256
          name: nginx-confmap
          optional: False
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: nginx
        image: varxn/k8s-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/openresty/nginx/conf
          name: nginxconf
          readOnly: true
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11'
        args:
          - '-nginx.scrape-uri=http://localhost/status'
        ports:
          - containerPort: 9113