apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-sql-configmap
  namespace: my-sample-namespace
data:
  database_host: mysql-service

---

apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: my-sample-namespace
  labels:
    app: wordpress
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: my-sample-namespace
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: varxn/k8s-wp:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: wp-sql-configmap
              key: database_host
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim